### ISSUE TITLE
Control/status registers

### ISSUE THREAD

**Issue by nmigen-issue-migration** [amaranth-lang/amaranth-soc#1]
<a href="https://github.com/whitequark"><img src="https://avatars1.githubusercontent.com/u/54771?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [whitequark](https://github.com/whitequark)**
_Tuesday Sep 10, 2019 at 09:50 GMT_
_Originally opened as https://github.com/m-labs/nmigen-soc/issues/1_

----

Let's collect requirements for CSRs here.

Overview of oMigen design:
  * Two kinds of registers: `CSRStatus` (R/O) and `CSRStorage` (R/W);
  * Located on the dedicated CSR bus;
  * Does not support atomic reads or writes;
  * Includes ad-hoc support for generating C and Rust code, and dumping to CSV;
  * Does not have any support for generating documentation;
  * `AutoCSR` collects CSRs from submodules via Python introspection;
  * `CSRConstant` allows specifying limited supplementary data in generated code.

According to @sbourdeauducq, the primary semantic problem with oMigen CSR design is that it lacks atomicity, and fixing that would involve ditching the CSR bus and instead using Wishbone directly.

According to @mithro and @xobs, a significant problem with oMigen CSR design is that it does not allow generating documentation.

According to @whitequark, a problem with oMigen CSR design is that the code generation is very tightly coupled to MiSoC internals, and is quite hard to maintain.

**Comment by jfng** [comment]
Implemented by #68.
